### ISSUE TITLE
Add documentation for online region

### ISSUE THREAD

**Issue by geoffrey-wu** [quizbowl/collegecalendar#12]
The online "region" is defined as `0P`, but there is no mention of this in the map/regions.js file or the README. It would be useful to include this somewhere so people don't have to guess / snoop around the source code.

**Comment by hftf** [comment]
Thanks for the report! Iirc, `0P` is for online playtests, and `0L` is for online (not playtest). Would you like to make a PR to add some documentation?

**Comment by hftf** [comment]
I forgot: There are also tooltips in the main table if you hover over a region, though it doesn't count much for documentation. (See also #5 for an idea of a graphical tooltip, which already has at least an existing janky implementation.)

**Comment by hftf** [comment]
Addressed in 4ccacc0.
