### ISSUE TITLE
Eliminate horizontal scrolling

### ISSUE THREAD

**Issue by hftf** [quizbowl/collegecalendar#2]
Solving this issue will be tricky: we’re trying to present a lot of related information in a limited space. Here are some ideas, but post below if you have any better ones:

* Abandon the one-table-per-semester layout (from Jacob)
  * Why not put nationals and/or their qualifiers in a separate table? (from Jacob)
    * A calendar should be primarily chronological (easier to see what tournament is up next)
  * Split the current tables after every 3 tournaments?
    Tables would be at most 900 pixels wide, which is definitely reasonable.

Some advantages of the current table layout:

* A table does make it easy to compare values for different tournaments. If every tournament had its own section, you would have to scroll down a lot just to compare values.
* Narrower columns are not really an option, since text must fit legibly in the cells.

**Comment by ryanrosenberg** [comment]
What about a Gantt chart of tournaments for each semester, color-coded for difficulty? The bars for each tournament could then link to a more in-depth description of the tournament.

**Comment by hftf** [comment]
I like that idea. A temporal visualization (Gantt chart, calendar) would help people conceptualize the calendar and provide internal navigation. However, I’m having trouble seeing it as a full replacement for the main table.

* Start/end dates are frequently unknown, so the visualization itself cannot be the primary navigation.
* Splitting tournaments into pages defeats much of the purpose of the site (quick review/comparison on a single bookmarkable page), and forum announcements already exist for that purpose.
  * (That’s one interpretation of “link to a more in-depth description,” which could also mean links that jump to anchors on the same page, or buttons that toggle modal interaction like pop-ups.)

**Comment by ryanrosenberg** [comment]
Re: point #2, I was envisioning either of the latter two options, I agree
that a page per tournament would be overkill.

Specific mirror dates are often unknown, but editors will generally publish
a date range during which they will be accepting mirrors. Perhaps that
range could be indicated by a bar, with additional marks for scheduled
mirrors?

**Comment by geoffrey-wu** [comment]
Would it make sense to transpose the tables? Vertical scrolling is more natural than horizontal scrolling.

**Comment by hftf** [comment]
While I'm sympathetic to the issue, I think there are still some use cases for horizontal scrolling, such as this very website – and most devices these days seem to have larger screens and trackpads that allow for natural horizontal scrolling. I'm not convinced that transposing is better: reading across a row is much less natural than reading down a column, because text is naturally longer in the horizontal dimension and so a column has a rectangular block gestalt that a row does not. A transposed table would make more sense if one wanted the values in different rows of the same column to be "compared", but that doesn't really apply to this table at all. The one suggestion so far to partition the table in groups of 3 or whatever seems the most promising, though I'm not sold on its need. Displaying a huge amount of tabular information on mobile is not going to be natural with almost any design anyway, although it could still stand to be much improved.

The Gantt-like summary table suggested above was added 2 years ago in 26a3b1b5 and has been iterated upon since.

I'll close the issue for now, but more specific proposals are still definitely welcome, open an issue/PR or reopen this issue.
